env:
    BUILDKITE_CLEAN_CHECKOUT: true

steps:
    - label: 'What packages have been changed?'
      plugins:
          - chronotc/monorepo-diff#v1.1.1:
                wait: true
                diff: 'git --no-pager diff --name-only refs/heads/master..refs/remotes/origin/$BUILDKITE_BRANCH'
                watch:
                    - path: ['packages/website', '.buildkite/pipelines/website']
                      config: { trigger: 'website' }
