steps:
    - label: Install Dependencies
      plugins: [docker#v3.5.0: { image: 'node:lts' }]
      commands:
          - cd packages/website && yarn
    - wait
    - label: Lint
      plugins: [docker#v3.5.0: { image: 'node:lts' }]
      commands:
          - yarn website:lint
    # Deploy
    # - label: Install Now CLI
    #   command: npm install --global --unsafe-perm now
    #   plugins: [docker#v3.5.0: { image: 'node:lts' }]
