steps:
    - label: Lint
      key: lint
      command: yarn && yarn website:lint
      plugins: [docker#v3.5.0: { image: 'node:lts' }]

    - label: Build
      key: build
      depends_on: lint
      plugins: [docker#v3.5.0: { image: 'node:lts' }]
      command: yarn && yarn website:build
    # Deploy
    # - label: Install Now CLI
    #   command: npm install --global --unsafe-perm now
    #   plugins: [docker#v3.5.0: { image: 'node:lts' }]
